defaults: &defaults
 docker:
   - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
 working_directory: ~/app

version: 2
jobs:
 lint:
   <<: *defaults
   steps:
     - checkout
     - run:
        name: RubyLint
        command: echo "this is where you should lint"
     - run:
         name: Rubocop
         command: rubocop

  style:
     <<: *defaults
     steps:
       - checkout
       - run:
          name: Rubocop
          command: rubocop

  unit:
     <<: *defaults
     steps:
       - checkout
       - run:
          name: RSpec
          command: echo "this is where you should unit test"

  build_and_deploy:
     <<: *defaults
     steps:
       - checkout
       - run:
          name: RSpec
          command: echo "this is where you should unit test"


workflows:
 version: 2
 commit:
   jobs:
     - lint
     - style
     - unit
     - build_and_deploy:
        filters:
          branches:
            only:
              - master
        requires:
          - lint
          - style
          - unit
          - hold

