defaults: &defaults
 docker:
   - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
 working_directory: ~/app

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
         name: RubyLint
         command: echo "this is where you should lint"

  style:
     <<: *defaults
     steps:
       - checkout
       - run:
          name: Rubocop
          command: |
            ls -la
            rubocop


  unit:
     <<: *defaults
     steps:
       - checkout
       - run:
          name: RSpec
          command: echo "this is where you should unit test"

  build_and_deploy:
     <<: *defaults
     steps:
       - checkout
       - run:
          name: Bundle, Zip, and Upload to S3
          command: |
            echo 'running bundler install command'
            echo 'zipping up the scripts and vendor directories'
            echo 'uploading to an s3 bucket for lambda deployment'


workflows:
 version: 2
 commit:
   jobs:
     - lint
     - style
     - unit
     - hold:
          type: approval
          requires:
           - lint
           - style
           - unit
     - build_and_deploy:
        filters:
          branches:
            only:
              - master
        requires:
          - hold

