defaults: &defaults
 docker:
   - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
 working_directory: ~/app

version: 2
jobs:
 lint_and_style:
   <<: *defaults
   steps:
     - checkout
     - run:
         name: WTF
         command: |
          ruby --version
          gem --version
          gem list


workflows:
 version: 2
 commit:
   jobs:
     - lint_and_style

